### ISSUE TITLE
A Readme needed

### ISSUE THREAD

**Issue by JigaoLuo** [LibertyPaul/HybridLargeDataStorage#1]
Hi
Can you explain this repo a little bit?

**Comment by LibertyPaul** [comment]
Hi, certainly I can. But please give a few points why do you want to use it.

**Comment by JigaoLuo** [comment]
I would like to get some idea for my thesis, which is also about the data layout (storage, data format) in DBMS.

**Comment by LibertyPaul** [comment]
Done. Please let me know in case any additional clarification is needed.
